PYTHONIOENCODING=utf-8 python3 -m nmt.nmt \
       --attention=scaled_luong \
       --src=en --tgt=cn \
       --vocab_prefix=/home/ubuntu/ai-translation/data/vocab  \
       --train_prefix=/home/ubuntu/ai-translation/data/train \
       --dev_prefix=/home/ubuntu/ai-translation/data/dev  \
       --test_prefix=/home/ubuntu/ai-translation/data/test \
       --out_dir=/home/ubuntu/ai-translation/translate_model \
       --num_train_steps=12000 \
       --steps_per_stats=100 \
       --num_layers=2 \
       --num_units=128 \
       --dropout=0.2 \
       --metrics=bleu
